package main

// MinimalGoModTemplate returns the go.mod file content for minimal template.
// This template excludes JWT and authentication-related dependencies.
func (t *ProjectTemplates) MinimalGoModTemplate() string {
	// Get the appropriate database driver dependency
	databaseDriver := GoModDependencies(t.database)

	return `module ` + t.projectName + `

go 1.25.5

require (
	github.com/go-playground/validator/v10 v10.30.1
	github.com/gofiber/fiber/v2 v2.52.10
	github.com/joho/godotenv v1.5.1
	github.com/rs/zerolog v1.33.0
	github.com/swaggo/fiber-swagger v1.3.0
	github.com/swaggo/swag v1.16.4
	go.uber.org/fx v1.24.0
	` + databaseDriver + `
	gorm.io/gorm v1.31.1
)
`
}

// MinimalMainGoTemplate returns the cmd/main.go file content for minimal template.
// This template has no auth modules, only basic infrastructure.
func (t *ProjectTemplates) MinimalMainGoTemplate() string {
	return `package main

import (
	"log"

	"github.com/joho/godotenv"
	"go.uber.org/fx"

	"` + t.projectName + `/internal/infrastructure/database"
	"` + t.projectName + `/internal/infrastructure/server"
	"` + t.projectName + `/pkg/logger"
)

// @title ` + t.projectName + ` API
// @version 1.0
// @description A minimal Go API with Fiber, GORM, and Swagger
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@example.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8080
// @BasePath /

func main() {
	// Load environment variables from .env file
	// This is primarily for local development; in production, use system environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found or couldn't be loaded")
	}

	fx.New(
		// Core infrastructure
		logger.Module,
		database.Module,

		// HTTP server (must be last as it depends on other modules)
		server.Module,
	).Run()
}
`
}

// MinimalRoutesTemplate returns the internal/adapters/http/routes.go for minimal template.
// This template only has health and swagger routes, no auth endpoints.
func (t *ProjectTemplates) MinimalRoutesTemplate() string {
	return `// Package http provides HTTP route registration and health check endpoints.
package http

import (
	"github.com/gofiber/fiber/v2"
	swagger "github.com/swaggo/fiber-swagger"

	// Swagger docs - generated by swag init
	_ "` + t.projectName + `/docs"
)

// RegisterRoutes configures all application routes.
// For minimal template, this includes only health and swagger endpoints.
func RegisterRoutes(app *fiber.App) {
	// Health check
	RegisterHealthRoutes(app)

	// Swagger documentation
	app.Get("/swagger/*", swagger.WrapHandler)
}
`
}

// MinimalServerTemplate returns the internal/infrastructure/server/server.go for minimal template.
// This template has no auth middleware dependencies.
func (t *ProjectTemplates) MinimalServerTemplate() string {
	return `// Package server provides HTTP server configuration and lifecycle management.
// It creates and configures a Fiber application with middleware, error handling,
// and graceful shutdown support through fx lifecycle hooks.
package server

import (
	"context"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/rs/zerolog"
	"go.uber.org/fx"

	"` + t.projectName + `/pkg/config"
	httpRoutes "` + t.projectName + `/internal/adapters/http"

	// Swagger docs - generated by swag init
	_ "` + t.projectName + `/docs"
)

// Module provides the Fiber server dependency via fx with automatic lifecycle management.
var Module = fx.Module("server",
	fx.Provide(NewServer),
	fx.Invoke(registerHooks),
)

// NewServer creates and configures a new Fiber application for minimal template.
// It sets up the application name and common middleware without auth.
func NewServer(log zerolog.Logger) *fiber.App {
	app := fiber.New(fiber.Config{
		AppName: "` + t.projectName + `",
		// Increase buffer sizes to prevent "Request Header Fields Too Large" errors
		ReadBufferSize:  16384, // 16KB (default is 4KB)
		WriteBufferSize: 16384,
	})

	// Add recovery middleware to prevent crashes
	app.Use(recover.New())

	// Add request logging middleware
	app.Use(logger.New(logger.Config{
		Format: "[${time}] ${status} - ${method} ${path} ${latency}\n",
	}))

	// Ignore common browser requests (favicon, apple-touch-icon)
	// These would otherwise pollute error logs
	app.Get("/favicon.ico", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusNoContent)
	})
	app.Get("/apple-touch-icon*.png", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusNoContent)
	})

	// Register routes
	httpRoutes.RegisterRoutes(app)

	log.Info().Msg("Fiber server initialized (minimal template)")

	return app
}

// registerHooks registers fx lifecycle hooks for server startup and graceful shutdown.
func registerHooks(lifecycle fx.Lifecycle, app *fiber.App, log zerolog.Logger) {
	lifecycle.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			port := config.GetEnv("APP_PORT", "8080")
			log.Info().Str("port", port).Msg("Starting Fiber server")

			// Start server in background goroutine
			go func() {
				if err := app.Listen(":" + port); err != nil {
					log.Error().Err(err).Msg("Server stopped unexpectedly")
				}
			}()

			return nil
		},
		OnStop: func(ctx context.Context) error {
			log.Info().Msg("Shutting down Fiber server gracefully")
			return app.ShutdownWithContext(ctx)
		},
	})
}
`
}

// MinimalEnvTemplate returns the .env.example file content for minimal template.
// This template has no JWT-related configuration.
func (t *ProjectTemplates) MinimalEnvTemplate() string {
	return `# Application Configuration
APP_NAME=` + t.projectName + `
APP_ENV=development
APP_PORT=8080

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=` + t.projectName + `
DB_SSLMODE=disable
`
}

// MinimalReadmeTemplate returns the README.md file content for minimal template.
// This template focuses on basic API features without authentication.
func (t *ProjectTemplates) MinimalReadmeTemplate() string {
	return `# ` + t.projectName + `

Application backend Go générée avec create-go-starter (template minimal). API REST simple avec Swagger et PostgreSQL.

## Fonctionnalités

- **API REST** avec Fiber v2 - Framework web haute performance
- **Base de données** - GORM avec PostgreSQL et migrations automatiques
- **Injection de dépendances** - uber-go/fx pour architecture modulaire
- **Documentation Swagger** - API documentée automatiquement avec OpenAPI
- **Docker** - Build multi-stage optimisé
- **Logging structuré** - rs/zerolog pour logs professionnels
- **Health check** - Endpoint /health pour monitoring

## Prérequis

- **Go 1.25+** - [Télécharger](https://golang.org/dl/)
- **PostgreSQL** - Base de données (peut être lancée via Docker)
- **Docker** (optionnel) - Pour containerisation
- **Make** - Pour les commandes de build
- **swag** (optionnel) - Pour régénérer la documentation Swagger
  ` + "```bash" + `
  go install github.com/swaggo/swag/cmd/swag@latest
  ` + "```" + `

## Installation rapide

### 1. Installer les dépendances

` + "```bash" + `
go mod tidy
` + "```" + `

### 2. Lancer PostgreSQL

**Option A: Docker (recommandé)**

` + "```bash" + `
docker run -d \
  --name postgres \
  -e POSTGRES_DB=` + t.projectName + ` \
  -e POSTGRES_PASSWORD=postgres \
  -p 5432:5432 \
  postgres:16-alpine
` + "```" + `

**Option B: PostgreSQL local**

` + "```bash" + `
# macOS
brew install postgresql
brew services start postgresql
createdb ` + t.projectName + `

# Linux
sudo apt install postgresql
sudo systemctl start postgresql
sudo -u postgres createdb ` + t.projectName + `
` + "```" + `

### 3. Lancer l'application

` + "```bash" + `
make run
` + "```" + `

L'API sera disponible sur ` + "`http://localhost:8080`" + `

### 4. Tester

` + "```bash" + `
# Health check
curl http://localhost:8080/health
` + "```" + `

## API Endpoints

### Health & Documentation

- ` + "`GET /health`" + ` - Health check
- ` + "`GET /swagger/*`" + ` - Documentation Swagger

## Architecture

Ce projet suit l'architecture hexagonale simplifiée:

` + "```" + `
` + t.projectName + `/
├── cmd/                     # Point d'entrée
│   └── main.go              # Bootstrap avec fx
├── internal/
│   ├── adapters/            # Adapters (HTTP)
│   │   └── http/            # Health handler et routes
│   └── infrastructure/      # Infrastructure
│       ├── database/        # Configuration DB
│       └── server/          # Configuration Fiber
├── pkg/                     # Packages réutilisables
│   ├── config/              # Configuration
│   └── logger/              # Logger
├── docs/                    # Documentation Swagger
├── .env                     # Configuration (créé automatiquement)
├── .env.example             # Template
├── Dockerfile               # Build Docker
├── Makefile                 # Commandes
└── go.mod                   # Dépendances
` + "```" + `

## Développement

### Commandes Make

| Commande | Description |
|----------|-------------|
| ` + "`make help`" + ` | Afficher l'aide |
| ` + "`make run`" + ` | Lancer l'application |
| ` + "`make build`" + ` | Compiler le binaire |
| ` + "`make test`" + ` | Tests avec race detector |
| ` + "`make lint`" + ` | golangci-lint |
| ` + "`make clean`" + ` | Nettoyer artifacts |
| ` + "`make swagger`" + ` | Générer docs Swagger |
| ` + "`make docker-build`" + ` | Build image Docker |
| ` + "`make docker-run`" + ` | Run conteneur Docker |

## Stack technique

| Composant | Bibliothèque | Description |
|-----------|-------------|-------------|
| Web Framework | [Fiber](https://gofiber.io/) v2 | Framework HTTP rapide |
| ORM | [GORM](https://gorm.io/) | ORM avec PostgreSQL |
| DI | [fx](https://uber-go.github.io/fx/) | Dependency injection |
| Logging | [zerolog](https://github.com/rs/zerolog) | Logger structuré |
| Swagger | [swaggo](https://github.com/swaggo/swag) | Documentation API |

## Variables d'environnement

Fichier ` + "`.env`" + `:

` + "```bash" + `
# Application
APP_NAME=` + t.projectName + `
APP_ENV=development
APP_PORT=8080

# Database
DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=` + t.projectName + `
DB_SSLMODE=disable
` + "```" + `

## Déploiement

### Docker

` + "```bash" + `
# Build
make docker-build

# Run
docker run -p 8080:8080 \
  -e DB_HOST=host.docker.internal \
  ` + t.projectName + `:latest
` + "```" + `

## Ajout de fonctionnalités

Ce template minimal est un point de départ. Pour ajouter des fonctionnalités:

1. **Pour ajouter l'authentification:** Utilisez le template ` + "`full`" + ` lors de la création du projet
2. **Pour ajouter des endpoints:** Créez vos handlers dans ` + "`internal/adapters/http/`" + `
3. **Pour ajouter des modèles:** Créez vos entités dans ` + "`internal/models/`" + `

## Licence

MIT

---

**Généré avec [create-go-starter](https://github.com/tky0065/go-starter-kit)** 🚀
`
}

// MinimalDatabaseTemplate returns the database.go for minimal template.
// This template has no User model migrations.
func (t *ProjectTemplates) MinimalDatabaseTemplate() string {
	// Get database-specific import path and description
	databaseImport := DatabaseImportPath(t.database)
	databaseDesc := t.getDatabaseDescription()
	connectionCode := DatabaseConnectionCode(t.database)

	// Generate database-specific DSN code
	var dsnCode string
	switch t.database {
	case "mysql":
		dsnCode = `dsn := fmt.Sprintf(
		"%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local",
		config.GetEnv("DB_USER", "root"),
		config.GetEnv("DB_PASSWORD", "secret"),
		config.GetEnv("DB_HOST", "localhost"),
		config.GetEnv("DB_PORT", "3306"),
		config.GetEnv("DB_NAME", "` + t.projectName + `"),
	)`
	case "sqlite":
		dsnCode = `dsn := fmt.Sprintf(
		"./%s.db",
		config.GetEnv("DB_NAME", "` + t.projectName + `"),
	)`
	default: // postgres
		dsnCode = `dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",
		config.GetEnv("DB_HOST", "localhost"),
		config.GetEnv("DB_PORT", "5432"),
		config.GetEnv("DB_USER", "postgres"),
		config.GetEnv("DB_PASSWORD", "postgres"),
		config.GetEnv("DB_NAME", "` + t.projectName + `"),
		config.GetEnv("DB_SSLMODE", "disable"),
	)`
	}

	return `// Package database provides ` + databaseDesc + ` database connectivity and management.
// It configures GORM for database operations, handles connection pooling,
// and manages graceful shutdown through fx lifecycle hooks.
package database

import (
	"context"
	"fmt"
	"time"

	"github.com/rs/zerolog"
	"go.uber.org/fx"
	"` + databaseImport + `"
	"gorm.io/gorm"

	"` + t.projectName + `/pkg/config"
)

// Module provides the database dependency via fx with automatic lifecycle management.
var Module = fx.Module("database",
	fx.Provide(NewDatabase),
	fx.Invoke(registerHooks),
)

// NewDatabase creates a new GORM database connection configured from environment variables.
// It establishes a database connection and configures connection pooling.
func NewDatabase(logger zerolog.Logger) (*gorm.DB, error) {
	// Build DSN from environment variables
	` + dsnCode + `

	db, err := gorm.Open(` + connectionCode + `, &gorm.Config{})
	if err != nil {
		return nil, fmt.Errorf("failed to connect to database: %w", err)
	}

	logger.Info().Msg("Successfully connected to database")

	// Configure connection pool
	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("failed to get database instance: %w", err)
	}

	// Set connection pool parameters
	sqlDB.SetMaxOpenConns(25)
	sqlDB.SetMaxIdleConns(5)
	sqlDB.SetConnMaxLifetime(5 * time.Minute)

	// Note: For minimal template, no models to migrate
	// Add your models here: db.AutoMigrate(&YourModel{})

	logger.Info().Msg("Database connection pool configured and ready")

	return db, nil
}

// registerHooks registers fx lifecycle hooks for graceful database shutdown.
func registerHooks(lifecycle fx.Lifecycle, db *gorm.DB, logger zerolog.Logger) {
	lifecycle.Append(fx.Hook{
		OnStop: func(ctx context.Context) error {
			logger.Info().Msg("Closing database connection")
			sqlDB, err := db.DB()
			if err != nil {
				return err
			}
			return sqlDB.Close()
		},
	})
}
`
}

// MinimalSetupScriptTemplate returns a simplified setup.sh for minimal template.
// This template has no JWT secret generation.
func (t *ProjectTemplates) MinimalSetupScriptTemplate() string {
	return `#!/bin/bash

# setup.sh - Automated setup script for ` + t.projectName + ` (minimal template)
# This script configures your development environment

set -e  # Exit on error

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Helper functions
print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_step() {
    echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}$1${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Welcome message
echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Configuration automatique de ` + t.projectName + ` (minimal)${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}\n"

# ============================================================================
# STEP 1: Check Prerequisites
# ============================================================================
print_step "Étape 1/4: Vérification des prérequis"

MISSING_DEPS=0

# Check Go
if command_exists go; then
    GO_VERSION=$(go version | awk '{print $3}')
    print_success "Go est installé: $GO_VERSION"
else
    print_error "Go n'est pas installé. Installez Go 1.25+ depuis https://golang.org/dl/"
    MISSING_DEPS=1
fi

# Check Docker (optional but recommended)
if command_exists docker; then
    print_success "Docker est installé"
    DOCKER_AVAILABLE=1
else
    print_info "Docker n'est pas installé (optionnel). PostgreSQL devra être installé localement."
    DOCKER_AVAILABLE=0
fi

if [ $MISSING_DEPS -eq 1 ]; then
    print_error "Des dépendances obligatoires sont manquantes. Installez-les et relancez ce script."
    exit 1
fi

# ============================================================================
# STEP 2: Install Go Dependencies
# ============================================================================
print_step "Étape 2/4: Installation des dépendances Go"

print_info "Exécution de 'go mod tidy'..."
if go mod tidy; then
    print_success "Dépendances Go installées avec succès"
else
    print_error "Échec de l'installation des dépendances Go"
    exit 1
fi

# Install swag CLI silently for Swagger documentation
if ! command_exists swag; then
    print_info "Installation de swag (générateur Swagger)..."
    go install github.com/swaggo/swag/cmd/swag@latest 2>/dev/null
    if command_exists swag; then
        print_success "swag installé avec succès"
    fi
fi

# ============================================================================
# STEP 3: Configure Environment
# ============================================================================
print_step "Étape 3/4: Configuration de l'environnement"

if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        print_success "Fichier .env créé depuis .env.example"
    else
        print_error ".env.example introuvable"
        exit 1
    fi
else
    print_info "Fichier .env existe déjà"
fi

# ============================================================================
# STEP 4: PostgreSQL Setup
# ============================================================================
print_step "Étape 4/4: Configuration de PostgreSQL"

if [ $DOCKER_AVAILABLE -eq 1 ]; then
    echo -n "Voulez-vous démarrer PostgreSQL avec Docker? (Y/n): "
    read -r USE_DOCKER
    if [[ ! $USE_DOCKER =~ ^[Nn]$ ]]; then
        if docker ps -a --format '{{.Names}}' | grep -q "^postgres$"; then
            print_info "Conteneur PostgreSQL existe déjà"
            if docker ps --format '{{.Names}}' | grep -q "^postgres$"; then
                print_success "PostgreSQL est déjà en cours d'exécution"
            else
                docker start postgres
                print_success "PostgreSQL démarré"
            fi
        else
            print_info "Création du conteneur PostgreSQL..."
            docker run -d \
                --name postgres \
                -e POSTGRES_DB=` + t.projectName + ` \
                -e POSTGRES_PASSWORD=postgres \
                -p 5432:5432 \
                postgres:16-alpine
            sleep 5
            print_success "PostgreSQL démarré avec Docker"
        fi
    fi
fi

# ============================================================================
# Summary
# ============================================================================
echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ✅ Configuration terminée avec succès!${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}\n"

print_info "Prochaines étapes:"
echo "  1. Lancer l'application:    make run"
echo "  2. Vérifier la santé:       curl http://localhost:8080/health"
echo "  3. Documentation Swagger:   http://localhost:8080/swagger/index.html"
echo ""
print_success "Bon développement! 🚀"
`
}

// MinimalDockerComposeTemplate returns simplified docker-compose for minimal template.
// No JWT_SECRET in environment variables.
func (t *ProjectTemplates) MinimalDockerComposeTemplate() string {
	return `version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: ` + t.projectName + `_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ` + t.projectName + `
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ` + t.projectName + `_network

  # Application API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ` + t.projectName + `_api
    environment:
      APP_NAME: ` + t.projectName + `
      APP_ENV: development
      APP_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ` + t.projectName + `
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ` + t.projectName + `_network
    command: /app/` + t.projectName + `

volumes:
  postgres_data:

networks:
  ` + t.projectName + `_network:
    driver: bridge
`
}

// MinimalDocsReadmeTemplate returns the docs/README.md for minimal template.
func (t *ProjectTemplates) MinimalDocsReadmeTemplate() string {
	return `# Documentation ` + t.projectName + `

Documentation pour le projet ` + t.projectName + ` (template minimal).

## Table des matières

1. [Démarrage rapide](./quick-start.md)

## Aide rapide

- **Lancer le projet**: ` + "`make run`" + `
- **Tests**: ` + "`make test`" + `
- **API Health**: ` + "`http://localhost:8080/health`" + `
- **Swagger UI**: ` + "`http://localhost:8080/swagger/index.html`" + `

## Ressources

- [create-go-starter Documentation](https://github.com/tky0065/go-starter-kit)
- [Fiber Documentation](https://docs.gofiber.io/)
- [GORM Documentation](https://gorm.io/docs/)
`
}

// MinimalQuickStartTemplate returns the docs/quick-start.md for minimal template.
func (t *ProjectTemplates) MinimalQuickStartTemplate() string {
	return `# Démarrage rapide

Guide pour lancer ` + t.projectName + ` en 5 minutes.

## Prérequis

- Go 1.25+
- PostgreSQL (ou Docker)

## Installation

### 1. Installer les dépendances

` + "```bash" + `
go mod tidy
` + "```" + `

### 2. Configurer la base de données

**Option A: Docker (Recommandé)**

` + "```bash" + `
docker run -d \
  --name postgres \
  -e POSTGRES_DB=` + t.projectName + ` \
  -e POSTGRES_PASSWORD=postgres \
  -p 5432:5432 \
  postgres:16-alpine
` + "```" + `

**Option B: PostgreSQL local**

` + "```bash" + `
# macOS
brew install postgresql && brew services start postgresql
createdb ` + t.projectName + `

# Linux
sudo apt install postgresql && sudo systemctl start postgresql
sudo -u postgres createdb ` + t.projectName + `
` + "```" + `

### 3. Lancer l'application

` + "```bash" + `
make run
` + "```" + `

L'API sera disponible sur ` + "`http://localhost:8080`" + `

### 4. Tester

` + "```bash" + `
# Health check
curl http://localhost:8080/health
# {"status":"ok"}
` + "```" + `

## Endpoints disponibles

- ` + "`GET /health`" + ` - Health check
- ` + "`GET /swagger/*`" + ` - Documentation Swagger

## Développement

### Commandes utiles

` + "```bash" + `
# Lancer l'app
make run

# Tests
make test

# Build
make build

# Docker
make docker-build
make docker-run
` + "```" + `

## Prochaines étapes

- Ajoutez vos propres endpoints dans ` + "`internal/adapters/http/`" + `
- Créez vos modèles de données dans ` + "`internal/models/`" + `
- Déployez avec Docker: ` + "`make docker-build && make docker-run`" + `

Bon développement! 🚀
`
}
